---
- name: PreReqs
  yum:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop: [ 'device-mapper-persistent-data', 'lvm2']


- name: Install Docker
  yum:
    update_cache: yes
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop: [ 'docker-ce-18.09.5']
  notify: Start Docker

- name: cgroup
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json

- name: daemon-reload
  service:
    name: daemon
    state: reloaded

- name: relaod service 
  service: 
    name: docker
    state: restarted 
...
