---
- name: Get Join Command
  when: inventory_hostname == "M"
  shell: kubeadm token create --print-join-command
  register: join_command_raw

- name: Set Join Command
  when: inventory_hostname == "M"
  set_fact:
    join_command: "{{ join_command_raw.stdout_lines[0] }}"

- name: Join Cluster
  when: inventory_hostname in groups['Worker']
  shell: "{{ hostvars['M'].join_command }} >> NodeJoined.txt"
  args:
    chdir: $HOME
    creates: NodeJoined.txt
...
