---
- name: Setup Kubernetes
  hosts: all
  gather_facts: False
  roles:
    - role: preup
      become: true
      tags:
        - all
        - update

    - role: docker
      become: true
      tags:
        - all
        - docker

    - role: group
      become: true
      tags:
        - all
        - group

    - role: swap
      become: true
      tags:
        - all
        - swap

    - role: kube
      become: true
      tags:
        - all
        - kube
...
