---
- name: Add Docker Repo
  command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

- name: Install Docker
  yum:
    name: docker-ce-18.09.5
    state: present
    update_cache: yes

- name: Start Docker
  become: true
  service:
    name: docker
    state: started
    enabled: yes
